apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: elimination
        task: frontend

spec:
    replicas: 2
    selector:
        matchLabels:
            app: elimination
            task: frontend

    template:
        metadata:
            labels:
                app: elimination
                task: frontend
        spec:
            imagePullSecrets:
                -   name: regcred
            containers:
                -   name: frontend
                    image: ghcr.io/gunn-elimination/elimination-2023/frontend:${{ env.FRONTEND_VERSION }}
                    ports:
                        -   containerPort: 80
                    env:
                        -   name: PORT
                            value: "80"
                    envFrom:
                        -   secretRef:
                                name: elimination-2023-frontend
                    resources:
                        requests:
                            memory: "128Mi"
                            cpu: "100m"
                        limits:
                            memory: "256Mi"
                            cpu: "200m"

                    readinessProbe:
                        httpGet:
                            path: /
                            port: 80
                        initialDelaySeconds: 60
                        periodSeconds: 10

                    volumeMounts:
                        -   name: spring-yml-config
                            mountPath: /app
                            subPath: application.yml