auth:
    username: "elimination"
    password: "elimination"
    database: "elimination"

primary:
    sidecars:
    -   name: ts-sidecar
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:v1.36"
        securityContext:
            runAsUser: 1000
            runAsGroup: 1000
        env:
            -   name: TS_KUBE_SECRET
                value: ""
            -   name: TS_USERSPACE
                value: "true"
            -   name: TS_AUTHKEY
                valueFrom:
                    secretKeyRef:
                        name: tailscale-auth
                        key: TS_AUTHKEY

metrics:
    enabled: true
    serviceMonitor:
        enabled: true
        labels:
            release: monitoring
        selector:
            matchLabels:
                app: elimination