name: Rebuild and redeploy frontend

on:
    push:
        branches:
            - k8s
        paths:
            - 'frontend/**'
            - '.github/workflows/k8s-update-frontend.yml'

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build the frontend image
                run: |
                    cd frontend
                    docker build -t ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }} .
                    docker push ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }}

            -   name: Update the frontend image
                uses: actions-hub/kubectl@master
                env:
                    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

                with:
                    args: set image deployment/frontend frontend=ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }}

            -   name: Update the frontend deployment
                uses: actions-hub/kubectl@master
                env:
                    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

                with:
                    args: rollout restart deployment/frontend