name: Rebuild and redeploy frontend

on:
    push:
        branches:
            - k8s
            - main
        paths:
            - 'frontend/**'
            - '.github/workflows/k8s-update-frontend.yml'

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to to the Container registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   uses: actions/checkout@v2
            -   name: Build the frontend image
                run: |
                    cd frontend
                    docker build -t ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }} .
                    docker tag ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }} ghcr.io/gunn-elimination/elimination-2023/frontend:latest
                    docker push ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }}
                    docker push ghcr.io/gunn-elimination/elimination-2023/frontend:latest

            -   name: Update the frontend image
                uses: actions-hub/kubectl@master
                env:
                    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

                with:
                    args: set image deployment/frontend frontend=ghcr.io/gunn-elimination/elimination-2023/frontend:${{ github.sha }}

            -   name: Update the frontend deployment
                uses: actions-hub/kubectl@master
                env:
                    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

                with:
                    args: rollout restart deployment/frontend